# Generated by Django 5.2.7 on 2025-11-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='predHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('hauteur', models.FloatField()),
                ('n_roues', models.IntegerField()),
                ('pred_result', models.IntegerField()),
            ],
        ),
    ]
