# Generated by Django 5.2.7 on 2025-11-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algoAI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
