# Generated by Django 5.2.7 on 2025-11-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algoAI', '0004_mlmodel_alter_predhistory_options_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='scaler_file',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
